# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 14:12
from __future__ import unicode_literals

import ShareSpace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareSpace', '0003_auto_20170320_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='date_from',
            field=models.DateField(default='2017-05-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='date_to',
            field=models.DateField(default='2018-05-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='photos',
            field=models.ImageField(default=' ', upload_to=ShareSpace.models.user_directory),
            preserve_default=False,
        ),
    ]
