# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 22:46
from __future__ import unicode_literals

import ShareSpace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareSpace', '0005_auto_20170406_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='photos',
            field=models.ImageField(blank=True, default=' ', upload_to=ShareSpace.models.user_directory),
            preserve_default=False,
        ),
    ]
