# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 23:01
from __future__ import unicode_literals

import ShareSpace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareSpace', '0006_auto_20170406_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=ShareSpace.models.user_directory),
        ),
    ]
