# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 14:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareSpace', '0008_auto_20170406_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='area_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')]),
        ),
    ]
